package it.awta.awtagest;

// Generated 14-mar-2011 23.50.10 by Hibernate Tools 3.4.0.CR1

/**
 * Insegnamento generated by hbm2java
 */
public class Insegnamento implements java.io.Serializable {

	private InsegnamentoId id;

	public Insegnamento() {
	}

	public Insegnamento(InsegnamentoId id) {
		this.id = id;
	}

	public InsegnamentoId getId() {
		return this.id;
	}

	public void setId(InsegnamentoId id) {
		this.id = id;
	}

}
