package it.awta.awtagest;

// Generated 14-mar-2011 23.50.10 by Hibernate Tools 3.4.0.CR1

/**
 * InsegnamentoId generated by hbm2java
 */
public class InsegnamentoId implements java.io.Serializable {

	private int sifuId;
	private int sgId;

	public InsegnamentoId() {
	}

	public InsegnamentoId(int sifuId, int sgId) {
		this.sifuId = sifuId;
		this.sgId = sgId;
	}

	public int getSifuId() {
		return this.sifuId;
	}

	public void setSifuId(int sifuId) {
		this.sifuId = sifuId;
	}

	public int getSgId() {
		return this.sgId;
	}

	public void setSgId(int sgId) {
		this.sgId = sgId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InsegnamentoId))
			return false;
		InsegnamentoId castOther = (InsegnamentoId) other;

		return (this.getSifuId() == castOther.getSifuId())
				&& (this.getSgId() == castOther.getSgId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSifuId();
		result = 37 * result + this.getSgId();
		return result;
	}

}
