package it.awta.awtagest;

// Generated 14-mar-2011 23.50.10 by Hibernate Tools 3.4.0.CR1

/**
 * IstruzioneId generated by hbm2java
 */
public class IstruzioneId implements java.io.Serializable {

	private int sgId;
	private int istId;

	public IstruzioneId() {
	}

	public IstruzioneId(int sgId, int istId) {
		this.sgId = sgId;
		this.istId = istId;
	}

	public int getSgId() {
		return this.sgId;
	}

	public void setSgId(int sgId) {
		this.sgId = sgId;
	}

	public int getIstId() {
		return this.istId;
	}

	public void setIstId(int istId) {
		this.istId = istId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IstruzioneId))
			return false;
		IstruzioneId castOther = (IstruzioneId) other;

		return (this.getSgId() == castOther.getSgId())
				&& (this.getIstId() == castOther.getIstId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSgId();
		result = 37 * result + this.getIstId();
		return result;
	}

}
