package it.awta.awtagest;

// Generated 14-mar-2011 23.50.10 by Hibernate Tools 3.4.0.CR1

/**
 * Istruzione generated by hbm2java
 */
public class Istruzione implements java.io.Serializable {

	private IstruzioneId id;

	public Istruzione() {
	}

	public Istruzione(IstruzioneId id) {
		this.id = id;
	}

	public IstruzioneId getId() {
		return this.id;
	}

	public void setId(IstruzioneId id) {
		this.id = id;
	}

}
