package it.awta.awtagest;

// Generated 16-apr-2011 16.31.09 by Hibernate Tools 3.4.0.Beta1

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Rinnovo generated by hbm2java
 */
public class Rinnovo implements java.io.Serializable {

	private Integer idRinnovo;
	private int sgCodeRinnovo;
	private Date dataRinnovo;
	private String stringRinnovo;
	private SimpleDateFormat formatter = new SimpleDateFormat("dd MMMM yyyy");

	public Rinnovo() {
	}

	public Rinnovo(int sgCodeRinnovo, Date dataRinnovo) {
		this.sgCodeRinnovo = sgCodeRinnovo;
		this.dataRinnovo = dataRinnovo;
		this.stringRinnovo = formatter.format(dataRinnovo);
	}

	public Integer getIdRinnovo() {
		return this.idRinnovo;
	}

	public void setIdRinnovo(Integer idRinnovo) {
		this.idRinnovo = idRinnovo;
	}

	public int getSgCodeRinnovo() {
		return this.sgCodeRinnovo;
	}

	public void setSgCodeRinnovo(int sgCodeRinnovo) {
		this.sgCodeRinnovo = sgCodeRinnovo;
	}

	public Date getDataRinnovo() {
		return this.dataRinnovo;
	}

	public void setDataRinnovo(Date dataRinnovo) {
		this.dataRinnovo = dataRinnovo;
	}
	
	public String getStringRinnovo() {
		return formatter.format(dataRinnovo);
	}

	public void setStringRinnovo(String stringRinnovo) {
		this.stringRinnovo = stringRinnovo;
	}

}
