package it.awta.awtagest;

// Generated 15-mar-2011 0.22.01 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Scuola generated by hbm2java
 */
public class Scuola implements java.io.Serializable {

	private Integer scId;
	private String scNome;
	private String scIndirizzo;
	private String scComune;
	private String scRegione;
	private String scNazione;
	private String scNote;
	private String scProvincia;
	private Set<Soggetto> soggettos = new HashSet<Soggetto>(0);

	public Scuola() {
	}

	public Scuola(String scNome, String scIndirizzo, String scComune,
			String scRegione, String scNazione, String scNote,
			String scProvincia, Set<Soggetto> soggettos) {
		this.scNome = scNome;
		this.scIndirizzo = scIndirizzo;
		this.scComune = scComune;
		this.scRegione = scRegione;
		this.scNazione = scNazione;
		this.scNote = scNote;
		this.scProvincia = scProvincia;
		this.soggettos = soggettos;
	}

	public Integer getScId() {
		return this.scId;
	}

	public void setScId(Integer scId) {
		this.scId = scId;
	}

	public String getScNome() {
		return this.scNome;
	}

	public void setScNome(String scNome) {
		this.scNome = scNome;
	}

	public String getScIndirizzo() {
		return this.scIndirizzo;
	}

	public void setScIndirizzo(String scIndirizzo) {
		this.scIndirizzo = scIndirizzo;
	}

	public String getScComune() {
		return this.scComune;
	}

	public void setScComune(String scComune) {
		this.scComune = scComune;
	}

	public String getScRegione() {
		return this.scRegione;
	}

	public void setScRegione(String scRegione) {
		this.scRegione = scRegione;
	}

	public String getScNazione() {
		return this.scNazione;
	}

	public void setScNazione(String scNazione) {
		this.scNazione = scNazione;
	}

	public String getScNote() {
		return this.scNote;
	}

	public void setScNote(String scNote) {
		this.scNote = scNote;
	}

	public String getScProvincia() {
		return this.scProvincia;
	}

	public void setScProvincia(String scProvincia) {
		this.scProvincia = scProvincia;
	}

	public Set<Soggetto> getSoggettos() {
		return this.soggettos;
	}

	public void setSoggettos(Set<Soggetto> soggettos) {
		this.soggettos = soggettos;
	}

}
