package it.awta.awtagest;

// Generated 15-mar-2011 0.22.01 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Sezione generated by hbm2java
 */
public class Sezione implements java.io.Serializable {

	private String sezNome;
	private String sezGrado;
	private Set<WsSezione> wsSeziones = new HashSet<WsSezione>(0);

	public Sezione() {
	}

	public Sezione(String sezNome) {
		this.sezNome = sezNome;
	}

	public Sezione(String sezNome, String sezGrado, Set<WsSezione> wsSeziones) {
		this.sezNome = sezNome;
		this.sezGrado = sezGrado;
		this.wsSeziones = wsSeziones;
	}

	public String getSezNome() {
		return this.sezNome;
	}

	public void setSezNome(String sezNome) {
		this.sezNome = sezNome;
	}

	public String getSezGrado() {
		return this.sezGrado;
	}

	public void setSezGrado(String sezGrado) {
		this.sezGrado = sezGrado;
	}

	public Set<WsSezione> getWsSeziones() {
		return this.wsSeziones;
	}

	public void setWsSeziones(Set<WsSezione> wsSeziones) {
		this.wsSeziones = wsSeziones;
	}

}
