package it.awta.awtagest;

// Generated 15-mar-2011 0.22.01 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Sifu generated by hbm2java
 */
public class Sifu implements java.io.Serializable {

	private int sifuId;
	private String sifuNome;
	private String sifuCognome;
	private Set<Soggetto> soggettos = new HashSet<Soggetto>(0);

	public Sifu() {
	}

	public Sifu(int sifuId) {
		this.sifuId = sifuId;
	}

	public Sifu(int sifuId, String sifuNome, String sifuCognome,
			Set<Soggetto> soggettos) {
		this.sifuId = sifuId;
		this.sifuNome = sifuNome;
		this.sifuCognome = sifuCognome;
		this.soggettos = soggettos;
	}

	public int getSifuId() {
		return this.sifuId;
	}

	public void setSifuId(int sifuId) {
		this.sifuId = sifuId;
	}

	public String getSifuNome() {
		return this.sifuNome;
	}

	public void setSifuNome(String sifuNome) {
		this.sifuNome = sifuNome;
	}

	public String getSifuCognome() {
		return this.sifuCognome;
	}

	public void setSifuCognome(String sifuCognome) {
		this.sifuCognome = sifuCognome;
	}

	public Set<Soggetto> getSoggettos() {
		return this.soggettos;
	}

	public void setSoggettos(Set<Soggetto> soggettos) {
		this.soggettos = soggettos;
	}

}
