package it.awta.awtagest;

// Generated 15-mar-2011 0.22.01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Soggetto generated by hbm2java
 */
public class Soggetto implements java.io.Serializable {

	private Integer sgId;
	private Sifu sifu;
	private Scuola scuola;
	private int sgCode;
	private Date sgIscrizione;
	private Date sgRinnovo;
	private String sgCognome;
	private String sgNome;
	private Date sgNascita;
	private String sgComunenasc;
	private String sgIndirizzo;
	private String sgComune;
	private String sgProvincia;
	private String sgRegione;
	private String sgNazione;
	private String sgNote;
	private String sgGrado;
	private String sgDettagli;
	private boolean sgDeleted;

	private Set<WsSezione> wsSeziones = new HashSet<WsSezione>(0);
	private Set<Istruttore> istruttores = new HashSet<Istruttore>(0);
	private Set<WtEsame> wtEsames = new HashSet<WtEsame>(0);
	private Set<Rinnovo> sgRinnovi = new HashSet<Rinnovo>(0);

	public Soggetto() {
	}

	public Soggetto(Scuola scuola, int sgCode, Date sgIscrizione,Date sgRinnovo,
			String sgCognome, String sgNome) {
		this.scuola = scuola;
		this.sgCode = sgCode;
		this.sgIscrizione = sgIscrizione;
		this.sgCognome = sgCognome;
		this.sgNome = sgNome;
		if(scuola!=null){
			this.sgDettagli = this.sgNome+ " | " + scuola.getScNome() + " | " + this.sgCode;
		}
	}

	public Soggetto(Sifu sifu, Scuola scuola, int sgCode, Date sgIscrizione,Date sgRinnovo,
			String sgCognome, String sgNome, Date sgNascita,
			String sgComunenasc, String sgIndirizzo, String sgComune,
			String sgProvincia, String sgRegione, String sgNazione,
			String sgNote, String sgGrado, Set<WsSezione> wsSeziones,
			Set<Istruttore> istruttores, Set<WtEsame> wtEsames, Set<Rinnovo> sgRinnovi,boolean sgDeleted) {
		this.sifu = sifu;
		this.scuola = scuola;
		this.sgCode = sgCode;
		this.sgIscrizione = sgIscrizione;
		this.sgRinnovo = sgRinnovo;
		this.sgCognome = sgCognome;
		this.sgNome = sgNome;
		this.sgNascita = sgNascita;
		this.sgComunenasc = sgComunenasc;
		this.sgIndirizzo = sgIndirizzo;
		this.sgComune = sgComune;
		this.sgProvincia = sgProvincia;
		this.sgRegione = sgRegione;
		this.sgNazione = sgNazione;
		this.sgNote = sgNote;
		this.sgGrado = sgGrado;
		this.wsSeziones = wsSeziones;
		this.istruttores = istruttores;
		this.wtEsames = wtEsames;
		this.sgRinnovi = sgRinnovi;
		if(scuola!=null){
			this.sgDettagli = this.sgNome+ " | " + scuola.getScNome() + " | " + this.sgCode;
		}
		this.sgDeleted = sgDeleted;
	}

	public Integer getSgId() {
		return this.sgId;
	}

	public void setSgId(Integer sgId) {
		this.sgId = sgId;
	}

	public Sifu getSifu() {
		return this.sifu;
	}

	public void setSifu(Sifu sifu) {
		this.sifu = sifu;
	}

	public Scuola getScuola() {
		return this.scuola;
	}

	public void setScuola(Scuola scuola) {
		this.scuola = scuola;
	}

	public int getSgCode() {
		return this.sgCode;
	}

	public void setSgCode(int sgCode) {
		this.sgCode = sgCode;
	}

	public Date getSgIscrizione() {
		return this.sgIscrizione;
	}

	public void setSgIscrizione(Date sgIscrizione){
		this.sgIscrizione = sgIscrizione;
	}

	public String getSgCognome() {
		return this.sgCognome;
	}

	public void setSgCognome(String sgCognome) {
		this.sgCognome = sgCognome;
	}

	public String getSgNome() {
		return this.sgNome;
	}

	public void setSgNome(String sgNome) {
		this.sgNome = sgNome;
	}

	public Date getSgNascita() {
		return this.sgNascita;
	}

	public void setSgNascita(Date sgNascita) {
		this.sgNascita = sgNascita;
	}

	public String getSgComunenasc() {
		return this.sgComunenasc;
	}

	public void setSgComunenasc(String sgComunenasc) {
		this.sgComunenasc = sgComunenasc;
	}

	public String getSgIndirizzo() {
		return this.sgIndirizzo;
	}

	public void setSgIndirizzo(String sgIndirizzo) {
		this.sgIndirizzo = sgIndirizzo;
	}

	public String getSgComune() {
		return this.sgComune;
	}

	public void setSgComune(String sgComune) {
		this.sgComune = sgComune;
	}

	public String getSgProvincia() {
		return this.sgProvincia;
	}

	public void setSgProvincia(String sgProvincia) {
		this.sgProvincia = sgProvincia;
	}

	public String getSgRegione() {
		return this.sgRegione;
	}

	public void setSgRegione(String sgRegione) {
		this.sgRegione = sgRegione;
	}

	public String getSgNazione() {
		return this.sgNazione;
	}

	public void setSgNazione(String sgNazione) {
		this.sgNazione = sgNazione;
	}

	public String getSgNote() {
		return this.sgNote;
	}

	public void setSgNote(String sgNote) {
		this.sgNote = sgNote;
	}

	public String getSgGrado() {
		return this.sgGrado;
	}

	public void setSgGrado(String sgGrado) {
		this.sgGrado = sgGrado;
	}

	public Set<WsSezione> getWsSeziones() {
		return this.wsSeziones;
	}

	public void setWsSeziones(Set<WsSezione> wsSeziones) {
		this.wsSeziones = wsSeziones;
	}

	public Set<Istruttore> getIstruttores() {
		return this.istruttores;
	}

	public void setIstruttores(Set<Istruttore> istruttores) {
		this.istruttores = istruttores;
	}

	public Set<WtEsame> getWtEsames() {
		return this.wtEsames;
	}

	public void setWtEsames(Set<WtEsame> wtEsames) {
		this.wtEsames = wtEsames;
	}
	public Set<Rinnovo> getSgRinnovi() {
		return this.sgRinnovi;
	}

	public void setSgRinnovi(Set<Rinnovo> sgRinnovi) {
		this.sgRinnovi = sgRinnovi;
	}
	public void setSgDettagli() {
		this.sgDettagli = this.sgNome+ " | " + this.scuola.getScNome();
	}
	public String getSgDettagli() {
		return this.sgNome+ " | " + scuola.getScNome() + " | " + this.sgCode;
	}
	public Date getSgRinnovo() {
		return sgRinnovo;
	}

	public void setSgRinnovo(Date sgRinnovo) {
		this.sgRinnovo = sgRinnovo;
	}
	public boolean isSgDeleted() {
		return sgDeleted;
	}

	public void setSgDeleted(boolean sgDeleted) {
		this.sgDeleted = sgDeleted;
	}
}
